# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egreeting.proto\"-\n\x0b\x43lientInput\x12\x10\n\x08greeting\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1f\n\x0cServerOutput\x12\x0f\n\x07message\x18\x01 \x01(\t\"9\n\nBookSearch\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x01(\t\"3\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\"<\n\x0bMovieSearch\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64irector\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x01(\t\"7\n\x05Movie\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64irector\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x32\x31\n\x07Greeter\x12&\n\x05greet\x12\x0c.ClientInput\x1a\r.ServerOutput\"\x00\x32*\n\tBookStore\x12\x1d\n\x05\x66irst\x12\x0b.BookSearch\x1a\x05.Book\"\x00\x32,\n\tMovieClub\x12\x1f\n\x05\x66irst\x12\x0c.MovieSearch\x1a\x06.Movie\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeting_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTINPUT']._serialized_start=18
  _globals['_CLIENTINPUT']._serialized_end=63
  _globals['_SERVEROUTPUT']._serialized_start=65
  _globals['_SERVEROUTPUT']._serialized_end=96
  _globals['_BOOKSEARCH']._serialized_start=98
  _globals['_BOOKSEARCH']._serialized_end=155
  _globals['_BOOK']._serialized_start=157
  _globals['_BOOK']._serialized_end=208
  _globals['_MOVIESEARCH']._serialized_start=210
  _globals['_MOVIESEARCH']._serialized_end=270
  _globals['_MOVIE']._serialized_start=272
  _globals['_MOVIE']._serialized_end=327
  _globals['_GREETER']._serialized_start=329
  _globals['_GREETER']._serialized_end=378
  _globals['_BOOKSTORE']._serialized_start=380
  _globals['_BOOKSTORE']._serialized_end=422
  _globals['_MOVIECLUB']._serialized_start=424
  _globals['_MOVIECLUB']._serialized_end=468
# @@protoc_insertion_point(module_scope)
